- name: installation of components
  apt: 
    name: memcached

- name: Memcached configuration
  ansible.builtin.lineinfile:
   state: present
   dest: /etc/memcached.conf
   regexp: "-1 127.0.0.1"
   line: "-1 10.0.0.11"

- name: memcached service restart
  shell:
    service memcached restart
